CREATE EXTENSION postgis;

CREATE TABLE filieres (id SERIAL UNIQUE, nom character varying(100));
INSERT INTO filieres (nom) VALUES ('Agriculture, Bois');
INSERT INTO filieres (nom) VALUES ('Architecture Paysage, Urbanisme');
INSERT INTO filieres (nom) VALUES ('Défense');
INSERT INTO filieres (nom) VALUES ('Sécurité');
INSERT INTO filieres (nom) VALUES ('Art-Design');
INSERT INTO filieres (nom) VALUES ('Arts du spectacle');
INSERT INTO filieres (nom) VALUES ('Culture et patrimoine');
INSERT INTO filieres (nom) VALUES ('Mode');
INSERT INTO filieres (nom) VALUES ('Assurance-Banque-Finance');
INSERT INTO filieres (nom) VALUES ('Audiovisuel');
INSERT INTO filieres (nom) VALUES ('Communication');
INSERT INTO filieres (nom) VALUES ('Edition-Librairie-Bibliothèque');
INSERT INTO filieres (nom) VALUES ('Traduction-Interprétation');
INSERT INTO filieres (nom) VALUES ('Bâtiments et travaux publics');
INSERT INTO filieres (nom) VALUES ('Compatibilité-Gestion-Ressources');
INSERT INTO filieres (nom) VALUES ('Droit-Justice');
INSERT INTO filieres (nom) VALUES ('Enseignement');
INSERT INTO filieres (nom) VALUES ('Recherche');
INSERT INTO filieres (nom) VALUES ('Energie');
INSERT INTO filieres (nom) VALUES ('Environnement-Qualité');
INSERT INTO filieres (nom) VALUES ('Logistique et transport');
INSERT INTO filieres (nom) VALUES ('Hôtellerie, restauration');
INSERT INTO filieres (nom) VALUES ('Tourisme');
INSERT INTO filieres (nom) VALUES ('Automobile');
INSERT INTO filieres (nom) VALUES ('Electronique');
INSERT INTO filieres (nom) VALUES ('Maintenance');
INSERT INTO filieres (nom) VALUES ('Mécanique');
INSERT INTO filieres (nom) VALUES ('Verre, béton, céramique-Matériaux');
INSERT INTO filieres (nom) VALUES ('Génie Civil');
INSERT INTO filieres (nom) VALUES ('Génie industriel-Génie urbain');
INSERT INTO filieres (nom) VALUES ('Physique-Chimie');
INSERT INTO filieres (nom) VALUES ('Informatique & Réseaux');
INSERT INTO filieres (nom) VALUES ('Jeu vidéo');
INSERT INTO filieres (nom) VALUES ('Informatique et numérique');
INSERT INTO filieres (nom) VALUES ('Commerce, distribution');
INSERT INTO filieres (nom) VALUES ('Marketing, publicité');
INSERT INTO filieres (nom) VALUES ('Médical');
INSERT INTO filieres (nom) VALUES ('Paramédical');
INSERT INTO filieres (nom) VALUES ('Social');
INSERT INTO filieres (nom) VALUES ('Sport');
INSERT INTO filieres (nom) VALUES ('Management');
INSERT INTO filieres (nom) VALUES ('Mathématiques -Statistiques');
INSERT INTO filieres (nom) VALUES ('Siences et humaines et sociales');

CREATE TABLE ecoles (id SERIAL UNIQUE, nom character varying(50), site character varying(60), description character varying(2000));
INSERT INTO ecoles (nom, site, description) VALUES ('ENSG-Géomatique', 'http://www.ensg.eu/', 'Grande école d''ingénieurs qui forme des professionnels dans le filiere des technologies de l''information géographique et forestière : la géomatique\n - filieres d''enseignement : Informatique, géolocalisation, imagerie 3D, web cartographique… Débouchés dans de nombreux secteurs : technologies de l''information, aménagement des territoires, transports, urbanisme, énergie, environnement, défense, géodécisionnel...\n - Formations proposées : cycle de technicien supérieur, cycle d''ingénieur, licence professionnelle, masters et mastères spécialisés');
INSERT INTO ecoles (nom, site, description) VALUES ('UPEM', 'http://www.u-pem.fr/', 'Avec + de 20% de ses 12.000 étudiants en apprentissage, l''UPEM est la première université française en matière d''apprentissage.\n - 7 grands filieres d''enseignement : arts, lettres modernes, langues, économie et gestion, STAPS, sciences humaines et sociales, sciences et technologies\n - Une École d''Urbanisme de Paris (EUP) : première école de ce type en France et l''une des plus importantes d’Europe, est un centre de formation proposant un master unique « Urbanisme et Aménagement » qui accueille chaque année plus de 350 étudiants en M1 et M2 et plusieurs Diplômes d’Université de niveau Master\n - Une École Supérieure d''Ingénieurs (ESIPE-MLV)\n - Un Institut d’Administration des Entreprises (IAE Gustave Eiffel)\n - Un Institut Universitaire de Technologie (IUT) : 2 sites : Champssur-Marne et Meaux (une navette est prévue entre les 2 le jour de la JPO)');
INSERT INTO ecoles (nom, site, description) VALUES ('EAVT', 'http://www.marnelavallee.archi.fr/', 'École nationale supérieure d''architecture, sous la tutelle du ministère de la Culture, qui forme des architectes et des urbanistes :\n - Licence générale en architecture\n - Filières de master : Architecture & Expérience /Matières à penser / Métropoles / Transformation\n - Formation Structure & Architecture (passerelle pour le double cursus architecte-ingénieur)\n - Formations post-master : DSA d''architecte-urbaniste, DPEA Architecture post-carbone, Habilitation à la maîtrise d’œuvre\n - Admission en 1re année ouverte aux titulaires du baccalauréat (général, technologique et professionnel)');
INSERT INTO ecoles (nom, site, description) VALUES ('ESIEE Paris', 'https://www.esiee.fr/', 'L''école de l''innovation technologique\nESIEE Paris est l''école d''ingénieurs de la CCI Paris Île-de-France.\nElle forme des étudiants dans tous les filieres du numérique et des nouvelles technologies, de l''électronique jusqu''à l''informatique, des systèmes embarqués jusqu''à la cybersécurité en passant par la datascience et l''intelligence artificielle.\nElle forme également aux nouvelles applications du numérique à la santé, l''énergie, et l’environnement, ainsi qu''au management des technologies.');
INSERT INTO ecoles (nom, site, description) VALUES ('CFA Descartes', 'https://www.cfadescartes.fr/', 'Boostez votre formation supérieure et votre insertion professionnelle avec l''alternance !\n - 85 formations ouvertes en apprentissage avec l''UPEM, en DUT, BTS, Licence Pro, Licence 3, Master et Master 2 dans 14 secteurs : Automobile, Banque, Comptabilité, Commerce Vente, Communication, Web et Numérique, Marketing, Informatique Electronique, Industrie Energie, Qualité Environnement, Urbanisme et Construction, Immobilier, Ressources humaines, Management des entreprises, Santé-sport-ESS\n - Le CFA Descartes c''est : 25 ans d''expérience1800 apprentis/an ; +1000 entreprises partenaires ; 93% de diplômés et 91% d''insertion pro.');
INSERT INTO ecoles (nom, site, description) VALUES ('IUT Marne-la-Vallée', 'http://iut.u-pem.fr/', 'Pas de description');
INSERT INTO ecoles (nom, site, description) VALUES ('Communauté Université Paris-Est', 'http://www.univ-paris-est.fr/fr', 'Faire un doctorat : Université Paris-Est forme à et par la recherche.\n - Formation doctorale et délivrance du diplôme de doctorat (Bac+8) et de l''habilitation à diriger des recherches\n - 8 écoles doctorales pluridisciplinaires : Agriculture alimentation biologie environnement santé ; Cultures et Sociétés ; Organisations marchés institutions ; Mathématiques et STIC ; Santé Publique ; Sciences Ingénierie Environnement ; Sciences de la vie et de la santé ; Ville transports et territoires.');
INSERT INTO ecoles (nom, site, description) VALUES ('Compagnons du devoir et du tour de France', 'https://www.compagnons-du-devoir.com/', '« Savoir-faire et savoir-être ». Se former et s''épanouir dans et par son métier :\n - En alternance : formation par le travail en entreprise, complété par des stages\n - En voyageant grâce au Tour de France, dont une étape à l''international\n - En partageant des expériences et des moments de vie en communauté\n - 30 métiers, 6 filières : Aménagement et finition ; Bâtiment ; Métiers du goût ; Matériaux souples ; Métallurgie et industrie ; Métiers du vivant. De la formation initiale (CAP, Bac pro) à la formation supérieure (DEUST, Licence pro).');
INSERT INTO ecoles (nom, site, description) VALUES ('ESO Paris SUPOSTEO', 'https://www.eso-suposteo.fr/', 'L''école d''ostéopathie référente en France et en Europe :\nDes conditions optimales pour former des ostéopathes passionnés et rigoureux. Un cursus complet en 4865 heures (5 ans) et la plus importante clinique ostéopathique de France.\n - Diplôme d''ostéopathe, titre national inscrit au RNCP niveau 1\n - Formation Bac+5');

CREATE TABLE batiments (id SERIAL UNIQUE, nom character varying(50), fonction character varying(30), lat float, lng float);
ALTER TABLE batiments ADD COLUMN geometrie geometry(POLYGON, 4326);
INSERT INTO batiments (nom, fonction, lat, lng, geometrie) VALUES ('ENSG', 'enseignement', 48.8410959, 2.5873874, ST_SetSRID(ST_GeomFromGeoJSON('{"type":"Polygon","coordinates":[[[2.5870136,48.8413843],[2.5870799,48.8407139],[2.5877388,48.8407423],[2.5876726,48.8414126],[2.5870136,48.8413843]]]}'),4326));
INSERT INTO batiments (nom, fonction, lat, lng, geometrie) VALUES ('Copernic', 'enseignement', 48.839159, 2.5866814, ST_SetSRID(ST_GeomFromGeoJSON('{"type":"Polygon","coordinates":[[[2.5862997,48.839662],[2.5862795,48.8396143],[2.5862746,48.8396016],[2.5862722,48.8395935],[2.5861187,48.8391168],[2.5860991,48.839115],[2.5860881,48.8391104],[2.5860835,48.8391028],[2.5860846,48.8390931],[2.5860886,48.8390874],[2.586096,48.8390832],[2.5861097,48.8390816],[2.5861291,48.8390821],[2.5861479,48.839082],[2.5861485,48.8390658],[2.5861287,48.839065],[2.5861539,48.8389134],[2.5866995,48.8389651],[2.5867088,48.8389084],[2.5866436,48.8389022],[2.5865302,48.8388899],[2.5865096,48.8388845],[2.586502,48.8388782],[2.586497,48.8388718],[2.5864967,48.8388576],[2.5865042,48.8388462],[2.5865188,48.8388385],[2.5865413,48.8388387],[2.586564,48.8388414],[2.5885563,48.8389872],[2.5885631,48.8389912],[2.5885674,48.838994],[2.5885688,48.8389996],[2.5885678,48.8390028],[2.5885664,48.8390085],[2.5885655,48.839014],[2.5885629,48.8390198],[2.5885541,48.8390245],[2.5885387,48.839026],[2.5883538,48.8390129],[2.5883422,48.8390782],[2.5885782,48.8390953],[2.5888947,48.839116],[2.5888765,48.8392519],[2.5888489,48.8392508],[2.5888481,48.8392697],[2.5888998,48.8392723],[2.5889134,48.8392769],[2.5889173,48.8392828],[2.5889188,48.8392889],[2.5889175,48.8392953],[2.5889119,48.8393019],[2.5889026,48.8393063],[2.5888886,48.8393065],[2.5888186,48.8393008],[2.5886875,48.8392918],[2.5885471,48.8392813],[2.588361,48.8392689],[2.5882737,48.8392621],[2.5882913,48.8393218],[2.5882972,48.8393419],[2.5883079,48.8393836],[2.5882652,48.8393894],[2.5882217,48.8393954],[2.5881792,48.8394013],[2.5880985,48.8394124],[2.5880141,48.839424],[2.5878933,48.8394406],[2.5878507,48.8394464],[2.5878103,48.839452],[2.5877284,48.8394632],[2.5875693,48.839486],[2.5875265,48.8394921],[2.5874512,48.8395028],[2.5874104,48.8395086],[2.5873717,48.8395142],[2.5873333,48.8395196],[2.5872558,48.8395307],[2.5871989,48.8395388],[2.5871561,48.839545],[2.5871173,48.8395505],[2.5870087,48.839566],[2.5869829,48.8395695],[2.5868595,48.8395862],[2.5867843,48.8395964],[2.5867475,48.8396014],[2.586709,48.8396066],[2.5866688,48.839612],[2.5866323,48.839617],[2.5865917,48.8396225],[2.5865557,48.8396273],[2.5865159,48.8396327],[2.5864007,48.8396483],[2.5862997,48.839662]]]}'),4326));
INSERT INTO batiments (nom, fonction, lat, lng, geometrie) VALUES ('EUP', 'enseignement', 48.842614, 2.5861283, null);
INSERT INTO batiments (nom, fonction, lat, lng, geometrie) VALUES ('EAVT', 'enseignement', 48.8411598, 2.5918843, ST_SetSRID(ST_GeomFromGeoJSON('{"type":"Polygon","coordinates":[[[2.592256,48.841301],[2.59225,48.841369],[2.592151,48.841364],[2.592143,48.841434],[2.591931,48.841424],[2.591939,48.841356],[2.591843,48.841351],[2.591836,48.84142],[2.591625,48.841411],[2.591633,48.841342],[2.591538,48.841339],[2.591538,48.841356],[2.591328,48.841351],[2.591346,48.841161],[2.591501,48.841166],[2.5915037,48.841138],[2.5915098,48.8410761],[2.5915114,48.84106],[2.591527,48.840901],[2.5916284,48.8409049],[2.592124,48.840924],[2.592121,48.840952],[2.592284,48.840955],[2.592276,48.84106],[2.592272,48.841101],[2.59226,48.841246],[2.592256,48.841301]]]}'),4326));
INSERT INTO batiments (nom, fonction, lat, lng, geometrie) VALUES ('ESIEE', 'enseignement', 48.8402383, 2.5816832, ST_SetSRID(ST_GeomFromGeoJSON('{"type":"Polygon","coordinates":[[[2.583935,48.8412575],[2.5825573,48.8410651],[2.5833169,48.8389725],[2.5830165,48.8385432],[2.5830797,48.8382207],[2.5836986,48.8382742],[2.5840144,48.8382919],[2.5842276,48.8382957],[2.5842326,48.8383874],[2.5843012,48.8384891],[2.5844214,48.8386134],[2.5845673,48.8387094],[2.5847733,48.8387716],[2.5847833,48.8387722],[2.5844222,48.83989],[2.58436,48.839899],[2.584285,48.839915],[2.584182,48.83995],[2.584103,48.839986],[2.584035,48.840029],[2.583975,48.840075],[2.583935,48.84012],[2.583897,48.840171],[2.583867,48.840228],[2.5838568,48.8402599],[2.58385,48.840281],[2.583845,48.840341],[2.583849,48.840406],[2.583863,48.84046],[2.583888,48.840512],[2.58393,48.840566],[2.583985,48.840624],[2.584073,48.840687],[2.584096,48.8407],[2.5841178,48.8407131],[2.583935,48.8412575]]]
}'),4326));
INSERT INTO batiments (nom, fonction, lat, lng, geometrie) VALUES ('CFA Descartes', 'enseignement', 48.8360343, 2.5923958, null);
INSERT INTO batiments (nom, fonction, lat, lng, geometrie) VALUES ('IUT Champs', 'enseignement', 48.837046, 2.5842788, ST_SetSRID(ST_GeomFromGeoJSON('{"type":"Polygon","coordinates":[[[2.5851427,48.8367804],[2.5855435,48.8368359],[2.5855305,48.8368768],[2.5853966,48.8372964],[2.5852567,48.8372971],[2.5851316,48.8373049],[2.5850053,48.837317],[2.5850132,48.8373358],[2.5848032,48.8373818],[2.5845759,48.8374582],[2.5845479,48.8374733],[2.5845073,48.8374952],[2.5844906,48.8375105],[2.5844045,48.8374445],[2.5842314,48.8374189],[2.5843002,48.8372088],[2.5839018,48.8371512],[2.5837925,48.8374777],[2.5834026,48.8374227],[2.5834221,48.8373652],[2.5836139,48.8368766],[2.5837324,48.8365748],[2.5841012,48.8366286],[2.5842365,48.8366483],[2.5851427,48.8367804]]]
}'),4326));
INSERT INTO batiments (nom, fonction, lat, lng, geometrie) VALUES ('MCDTF', 'enseignement', 48.8386772, 2.5896647, ST_SetSRID(ST_GeomFromGeoJSON('{"type": "Polygon","coordinates": [[[2.590178,48.8388136],[2.5897086,48.8389442],[2.5893599,48.8385435],[2.5899902,48.8384411],[2.590178,48.8388136]]]
}'),4326));
INSERT INTO batiments (nom, fonction, lat, lng, geometrie) VALUES ('ESO', 'enseignement', 48.836663, 2.5913698, ST_SetSRID(ST_GeomFromGeoJSON('{"type":"Polygon","coordinates":[[[2.591832,48.836889],[2.591785,48.836773],[2.592083,48.83672],[2.592015,48.836552],[2.591717,48.836604],[2.591667,48.836483],[2.592137,48.8364],[2.592275,48.836741],[2.592266,48.836742],[2.592272,48.836758],[2.592281,48.836756],[2.592301,48.836807],[2.592227,48.83682],[2.592224,48.836813],[2.592201,48.836818],[2.592204,48.836824],[2.591832,48.836889]]]
}'),4326));

CREATE TABLE formations (id SERIAL UNIQUE, nom character varying(200), niveau character varying(30), id_ecole INTEGER, id_batiment INTEGER, id_filiere INTEGER);
INSERT INTO formations (nom, niveau, id_ecole, id_batiment, id_filiere) VALUES ('M1&2 Forêt et bois', 'Master', 1, 1, 1);
INSERT INTO formations (nom, niveau, id_ecole, id_batiment, id_filiere) VALUES ('L1&2 Géographie et aménagement', 'Licence générale', 2, 2, 2);
INSERT INTO formations (nom, niveau, id_ecole, id_batiment, id_filiere) VALUES ('L3 Géographie et aménagement - Géographie sociale et culturelle', 'Licence générale', 2, 2, 2);
INSERT INTO formations (nom, niveau, id_ecole, id_batiment, id_filiere) VALUES ('L3 Géographie et aménagement - Etudes urbaines', 'Licence générale', 2, 2, 2);
INSERT INTO formations (nom, niveau, id_ecole, id_batiment, id_filiere) VALUES ('Métiers de l''aménagement du territoire et de l''urbanisme - Assistant chef de projet en aménagement de l''espace', 'Licence Professionnelle', 2, 2, 2);
INSERT INTO formations (nom, niveau, id_ecole, id_batiment, id_filiere) VALUES ('M1 Génie urbain', 'Master', 2, 2, 2);
INSERT INTO formations (nom, niveau, id_ecole, id_batiment, id_filiere) VALUES ('M2 Génie urbain  - Développement Urbain Durable (DUD)', 'Master', 2, 2, 2);
INSERT INTO formations (nom, niveau, id_ecole, id_batiment, id_filiere) VALUES ('M2 Génie urbain  - Ingénierie de la Maîtrise d’Œuvre Architecturale et Urbaine (IMOAU)', 'Master', 2, 2, 2);
INSERT INTO formations (nom, niveau, id_ecole, id_batiment, id_filiere) VALUES ('M1&2 Génie urbain - Management et Ingénierie des Services à l’Environnement (MISE)', 'Master', 2, 2, 2);
INSERT INTO formations (nom, niveau, id_ecole, id_batiment, id_filiere) VALUES ('M1 Urbanisme et aménagement', 'Master', 2, 3, 2);
INSERT INTO formations (nom, niveau, id_ecole, id_batiment, id_filiere) VALUES ('M2 Urbanisme et aménagement - Programmation, projet et management urbain', 'Master', 2, 3, 2);
INSERT INTO formations (nom, niveau, id_ecole, id_batiment, id_filiere) VALUES ('M2 Urbanisme et aménagement - Développement et Territoires: ressources, politiques et stratégies (DETER)', 'Master', 2, 3, 2);
INSERT INTO formations (nom, niveau, id_ecole, id_batiment, id_filiere) VALUES ('M2 Urbanisme et aménagement - Développement urbain intégré : stratégies et projets', 'Master', 2, 3, 2);
INSERT INTO formations (nom, niveau, id_ecole, id_batiment, id_filiere) VALUES ('M2 Urbanisme et aménagement - Alternatives urbaines, démarches expérimentales et Espaces publics (AUDE)', 'Master', 2, 3, 2);
INSERT INTO formations (nom, niveau, id_ecole, id_batiment, id_filiere) VALUES ('M2 Urbanisme et aménagement - Habitat et renouvellement urbain (HRU)', 'Master', 2, 3, 2);
INSERT INTO formations (nom, niveau, id_ecole, id_batiment, id_filiere) VALUES ('M2 Urbanisme et aménagement - Environnements urbains : stratégies, projets, services', 'Master', 2, 3, 2);
INSERT INTO formations (nom, niveau, id_ecole, id_batiment, id_filiere) VALUES ('M2 Urbanisme et aménagement - Transport, mobilité', 'Master', 2, 3, 2);
INSERT INTO formations (nom, niveau, id_ecole, id_batiment, id_filiere) VALUES ('M2 Urbanisme et aménagement - Urbanisme et expertise internationale', 'Master', 2, 3, 2);
INSERT INTO formations (nom, niveau, id_ecole, id_batiment, id_filiere) VALUES ('M2 Urbanisme et aménagement - Maîtrise d''ouvrage des projets urbains  (MOPU)', 'Master', 2, 3, 2);
INSERT INTO formations (nom, niveau, id_ecole, id_batiment, id_filiere) VALUES ('M1 Génie Civil', 'Master', 2, 2, 2);
INSERT INTO formations (nom, niveau, id_ecole, id_batiment, id_filiere) VALUES ('M2 Génie Civil - Mécanique, Matériaux et Structures pour la Construction et les Transports', 'Master', 2, 2, 2);
INSERT INTO formations (nom, niveau, id_ecole, id_batiment, id_filiere) VALUES ('M2 Génie Civil - Ingénierie de projet en Génie Civil', 'Master', 2, 2, 2);
INSERT INTO formations (nom, niveau, id_ecole, id_batiment, id_filiere) VALUES ('M2 Génie Civil - Mécanique des sols, des roches et des ouvrages dans leur environnement', 'Master', 2, 2, 2);
INSERT INTO formations (nom, niveau, id_ecole, id_batiment, id_filiere) VALUES ('M1&2 Géographie - Espaces, Sociétés, Territoires', 'Master', 2, 2, 2);
INSERT INTO formations (nom, niveau, id_ecole, id_batiment, id_filiere) VALUES ('M2 Histoire - Diagnostic historique et aménagement urbain', 'Master', 2, 2, 2);
INSERT INTO formations (nom, niveau, id_ecole, id_batiment, id_filiere) VALUES ('Diplôme d''études en architecture (DEEA)', 'Diplôme d''architecture', 3, 4, 2);
INSERT INTO formations (nom, niveau, id_ecole, id_batiment, id_filiere) VALUES ('Diplôme d''État d’architecte (ADE)', 'Diplôme d''architecture', 3, 4, 2);
INSERT INTO formations (nom, niveau, id_ecole, id_batiment, id_filiere) VALUES ('Diplôme de spécialisation et d''approfondissement en architecture « architecte-urbaniste »', 'Diplôme d''architecture', 3, 4, 2);
INSERT INTO formations (nom, niveau, id_ecole, id_batiment, id_filiere) VALUES ('Mastère spécialisé Photogrammétrie, positionnement et mesure de déformations', 'Mastère spécialisé', 1, 1, 2);
INSERT INTO formations (nom, niveau, id_ecole, id_batiment, id_filiere) VALUES ('Filière Systèmes électroniques intelligents', 'Diplôme d''ingénieur', 4, 5, 3);
INSERT INTO formations (nom, niveau, id_ecole, id_batiment, id_filiere) VALUES ('Diplôme d’ingénieur en géomatique', 'Diplôme d''ingénieur', 1, 1, 3);
INSERT INTO formations (nom, niveau, id_ecole, id_batiment, id_filiere) VALUES ('Filière Systèmes électroniques intelligents', 'Diplôme d''ingénieur', 4, 5, 4);
INSERT INTO formations (nom, niveau, id_ecole, id_batiment, id_filiere) VALUES ('L1 à L3 Arts - Musique et Métiers du Son', 'Licence générale', 2, 2, 5);
INSERT INTO formations (nom, niveau, id_ecole, id_batiment, id_filiere) VALUES ('L1 à L3 Arts - Études Visuelles, Multimédia et Arts Numériques', 'Licence générale', 2, 2, 5);
INSERT INTO formations (nom, niveau, id_ecole, id_batiment, id_filiere) VALUES ('Métiers du design - Design packaging et objet graphique', 'Licence Professionnelle', 2, 2, 5);
INSERT INTO formations (nom, niveau, id_ecole, id_batiment, id_filiere) VALUES ('Métiers du design - Management de Projets en Communication et Industries Graphiques', 'Licence Professionnelle', 2, 2, 5);
INSERT INTO formations (nom, niveau, id_ecole, id_batiment, id_filiere) VALUES ('M1&2 Arts, Lettres et Civilisations - Arts numériques et cultures visuelles', 'Master', 2, 2, 5);
INSERT INTO formations (nom, niveau, id_ecole, id_batiment, id_filiere) VALUES ('M1&2 Arts, Lettres et Civilisations - Musique et Informatique Musicale (MIM)', 'Master', 2, 2, 5);
INSERT INTO formations (nom, niveau, id_ecole, id_batiment, id_filiere) VALUES ('M1&2 Arts, Lettres et Civilisations - Création et arts sonores', 'Master', 2, 2, 5);
INSERT INTO formations (nom, niveau, id_ecole, id_batiment, id_filiere) VALUES ('M1&2 Arts, Lettres et Civilisations - Musique et Production musicale', 'Master', 2, 2, 5);
INSERT INTO formations (nom, niveau, id_ecole, id_batiment, id_filiere) VALUES ('L1 à L3 Arts - Cinéma et Audiovisuel', 'Licence générale', 2, 2, 6);
INSERT INTO formations (nom, niveau, id_ecole, id_batiment, id_filiere) VALUES ('M1&2 Arts, Lettres et Civilisations - Cinéma et audiovisuel (CAV)', 'Master', 2, 2, 6);
INSERT INTO formations (nom, niveau, id_ecole, id_batiment, id_filiere) VALUES ('Guide conférencier', 'Licence Professionnelle', 2, 2, 7);
INSERT INTO formations (nom, niveau, id_ecole, id_batiment, id_filiere) VALUES ('M1&2 Arts, Lettres et Civilisations - Littérature, Savoirs et Culture Numérique (LSCN)', 'Master', 2, 2, 7);
INSERT INTO formations (nom, niveau, id_ecole, id_batiment, id_filiere) VALUES ('Métiers de la mode', 'Licence Professionnelle', 2, 2, 8);
INSERT INTO formations (nom, niveau, id_ecole, id_batiment, id_filiere) VALUES ('M1 Finance Banque et assurance', 'Master', 2, 2, 9);
INSERT INTO formations (nom, niveau, id_ecole, id_batiment, id_filiere) VALUES ('M2 Mathématiques et applications - Finance', 'Master', 2, 2, 9);
INSERT INTO formations (nom, niveau, id_ecole, id_batiment, id_filiere) VALUES ('M1&2 Actuariat', 'Master', 2, 2, 9);
INSERT INTO formations (nom, niveau, id_ecole, id_batiment, id_filiere) VALUES ('Systèmes Audiovisuels Numériques', 'Licence Professionnelle', 6, 7, 10);
INSERT INTO formations (nom, niveau, id_ecole, id_batiment, id_filiere) VALUES ('Administration de Réseaux Scéniques', 'Licence Professionnelle', 6, 7, 10);
INSERT INTO formations (nom, niveau, id_ecole, id_batiment, id_filiere) VALUES ('Techniques du son et de l''image - Gestion de la production audiovisuelle', 'Licence Professionnelle', 2, 2, 10);
INSERT INTO formations (nom, niveau, id_ecole, id_batiment, id_filiere) VALUES ('Métiers du multimédia et de l''internet (MMI)', 'DUT', 6, 7, 11);
INSERT INTO formations (nom, niveau, id_ecole, id_batiment, id_filiere) VALUES ('Métiers de la Communication : chargé de communication des  collectivités territoriales et des associations', 'Licence Professionnelle', 2, 2, 11);
INSERT INTO formations (nom, niveau, id_ecole, id_batiment, id_filiere) VALUES ('Métiers du Tourisme : commercialisation des produits touristiques - Nouvelles technologies de l''Information et de la Communication (NTIC)', 'Licence Professionnelle',2, 2, 11);
INSERT INTO formations (nom, niveau, id_ecole, id_batiment, id_filiere) VALUES ('M1&2 Sciences sociales - Communication des entreprises et médias sociaux', 'Master', 2, 2, 11);
INSERT INTO formations (nom, niveau, id_ecole, id_batiment, id_filiere) VALUES ('L3 Lettres Modernes Appliquées', 'Licence générale', 2, 2, 12);
INSERT INTO formations (nom, niveau, id_ecole, id_batiment, id_filiere) VALUES ('Métiers du livre : édition et commerce du livre - Fabrication du livre imprimé et numérique', 'Licence Professionnelle', 2, 2, 12);
INSERT INTO formations (nom, niveau, id_ecole, id_batiment, id_filiere) VALUES ('Métiers du livre : édition et commerce du livre - Fabrication du livre imprimé et numérique', 'Licence Professionnelle', 2, 2, 12);
INSERT INTO formations (nom, niveau, id_ecole, id_batiment, id_filiere) VALUES ('M1&2 Métiers du livre et de l''édition - Edition Livre papier et numérique ', 'Master', 2, 2, 12);
INSERT INTO formations (nom, niveau, id_ecole, id_batiment, id_filiere) VALUES ('L1 à L3 Langues, littératures et civilisations étrangères et régionales - Anglais ou Espagnol', 'Licence générale', 2, 2, 13);
INSERT INTO formations (nom, niveau, id_ecole, id_batiment, id_filiere) VALUES ('L1&L2 Langues Etrangères appliquées - Anglais-Allemand ou Anglais-Espagnol', 'Licence générale', 2, 2, 13);
INSERT INTO formations (nom, niveau, id_ecole, id_batiment, id_filiere) VALUES ('L3 Langues Etrangères appliquées - Anglais-Allemand ou Anglais-Espagnol Traduction spécialisée', 'Licence générale', 2, 2, 13);
INSERT INTO formations (nom, niveau, id_ecole, id_batiment, id_filiere) VALUES ('M1&2 Traduction et interprétation - Traduction spécialisée', 'Master', 2, 2, 13);
INSERT INTO formations (nom, niveau, id_ecole, id_batiment, id_filiere) VALUES ('Compagnon du bâtiment durable', 'DU (Diplôme d''Université)', 6, 7, 14);
INSERT INTO formations (nom, niveau, id_ecole, id_batiment, id_filiere) VALUES ('Génie civil - Construction durable', 'DUT', 6, 7, 14);
INSERT INTO formations (nom, niveau, id_ecole, id_batiment, id_filiere) VALUES ('Géomètre-géomaticien', 'BTS', 1, 1, 14);
INSERT INTO formations (nom, niveau, id_ecole, id_batiment, id_filiere) VALUES ('Métiers de l''aménagement du territoire et de l''urbanisme - Assistant chef de projet en aménagement de l''espace', 'Licence Professionnelle', 2, 2, 14);
INSERT INTO formations (nom, niveau, id_ecole, id_batiment, id_filiere) VALUES ('Métiers du BTP : Génie civil et construction - Management de la conduite de travaux en bâtiment', 'Licence Professionnelle', 2, 2, 14);
INSERT INTO formations (nom, niveau, id_ecole, id_batiment, id_filiere) VALUES ('Métiers du BTP : Génie civil et construction - Projeteur en bureau d''études : Dessin, conception, modélisation-BIM', 'Licence Professionnelle', 2, 2, 14);
INSERT INTO formations (nom, niveau, id_ecole, id_batiment, id_filiere) VALUES ('Métiers du BTP : Génie civil et construction - Economie de la construction en contexte européen', 'Licence Professionnelle', 2, 2, 14);
INSERT INTO formations (nom, niveau, id_ecole, id_batiment, id_filiere) VALUES ('Métiers du BTP : Bâtiment et Construction - Conduite de Chantiers en Bâtiment (Maisons Individuelles)', 'Licence Professionnelle', 2, 2, 14);
INSERT INTO formations (nom, niveau, id_ecole, id_batiment, id_filiere) VALUES ('LP Chargé d''affaire en Agencement', 'Licence Professionnelle', 2, 2, 14);
INSERT INTO formations (nom, niveau, id_ecole, id_batiment, id_filiere) VALUES ('M1 Génie urbain', 'Master', 2, 2, 14);
INSERT INTO formations (nom, niveau, id_ecole, id_batiment, id_filiere) VALUES ('M2 Génie urbain  - Développement Urbain Durable (DUD)', 'Master', 2, 2, 14);
INSERT INTO formations (nom, niveau, id_ecole, id_batiment, id_filiere) VALUES ('M2 Génie urbain - Ingénierie de la Maîtrise d’Œuvre Architecturale et Urbaine (IMOAU)', 'Master', 2, 2, 14);
INSERT INTO formations (nom, niveau, id_ecole, id_batiment, id_filiere) VALUES ('M1&2 Génie urbain - Management et Ingénierie des Services à l’Environnement (MISE)', 'Master', 2, 2, 14);
INSERT INTO formations (nom, niveau, id_ecole, id_batiment, id_filiere) VALUES ('M1&2 Génie urbain - Management et Ingénierie des Services à l’Environnement (MISE)', 'Master', 2, 2, 14);
INSERT INTO formations (nom, niveau, id_ecole, id_batiment, id_filiere) VALUES ('Comptabilité gestion (CG)', 'BTS', 5, 6, 15);
INSERT INTO formations (nom, niveau, id_ecole, id_batiment, id_filiere) VALUES ('L1&L2 Economie et gestion', 'Licence générale', 2, 2, 15);
INSERT INTO formations (nom, niveau, id_ecole, id_batiment, id_filiere) VALUES ('L3 Economie et gestion - Gestion des entreprises', 'Licence générale', 2, 2, 15);
INSERT INTO formations (nom, niveau, id_ecole, id_batiment, id_filiere) VALUES ('L3 Economie et gestion - Économie', 'Licence générale', 2, 2, 15);
INSERT INTO formations (nom, niveau, id_ecole, id_batiment, id_filiere) VALUES ('L3 Economie et gestion - Management international', 'Licence générale', 2, 2, 15);
INSERT INTO formations (nom, niveau, id_ecole, id_batiment, id_filiere) VALUES ('L3 Economie et gestion - Comptabilité, contrôle et audit', 'Licence générale', 2, 2, 15);
INSERT INTO formations (nom, niveau, id_ecole, id_batiment, id_filiere) VALUES ('L3 Economie et gestion - Management commercial et de la relation client', 'Licence générale', 2, 2, 15);
INSERT INTO formations (nom, niveau, id_ecole, id_batiment, id_filiere) VALUES ('Management opérationnel des entreprises (MOE)', 'Licence Professionnelle', 5, 6, 15);
INSERT INTO formations (nom, niveau, id_ecole, id_batiment, id_filiere) VALUES ('Gestion et pilotage des ressources humaines (GPRH)', 'Licence Professionnelle', 6, 7, 15);
INSERT INTO formations (nom, niveau, id_ecole, id_batiment, id_filiere) VALUES ('Agencement - Chargé d''Affaires en Agencement', 'Licence Professionnelle', 2, 2, 15);
INSERT INTO formations (nom, niveau, id_ecole, id_batiment, id_filiere) VALUES ('Diplôme de comptabilité et de gestion (DCG)', 'DCG', 5, 6, 15);
INSERT INTO formations (nom, niveau, id_ecole, id_batiment, id_filiere) VALUES ('Diplôme supérieur de comptabilité et de gestion (DSCG)', 'DSCG', 5, 6, 15);
INSERT INTO formations (nom, niveau, id_ecole, id_batiment, id_filiere) VALUES ('M1 Intelligence économique', 'Master', 2, 2, 15);
INSERT INTO formations (nom, niveau, id_ecole, id_batiment, id_filiere) VALUES ('M2 Intelligence économique - Gestion des Connaissances, Patrimoine Immatériel et Innovation (GCPII)', 'Master', 2, 2, 15);
INSERT INTO formations (nom, niveau, id_ecole, id_batiment, id_filiere) VALUES ('M2 Intelligence économique - Influence, Lobbying et médias sociaux (ILMS)', 'Master', 2, 2, 15);
INSERT INTO formations (nom, niveau, id_ecole, id_batiment, id_filiere) VALUES ('M2 Intelligence économique - Intelligence Stratégique, Analyse des Risques et Territoires (ISART)', 'Master', 2, 2, 15);
INSERT INTO formations (nom, niveau, id_ecole, id_batiment, id_filiere) VALUES ('M1&2 Comptabilité, contrôle, audit', 'Master', 2, 2, 15);
INSERT INTO formations (nom, niveau, id_ecole, id_batiment, id_filiere) VALUES ('M1 Economie appliquée - Data Analyst', 'Master', 2, 2, 15);
INSERT INTO formations (nom, niveau, id_ecole, id_batiment, id_filiere) VALUES ('M2 Economie appliquée - Data Analyst Expertise de l''emploi et des RH', 'Master', 2, 2, 15);
INSERT INTO formations (nom, niveau, id_ecole, id_batiment, id_filiere) VALUES ('M2 Economie appliquée - Data Analyst Etudes de marché', 'Master', 2, 2, 15);
INSERT INTO formations (nom, niveau, id_ecole, id_batiment, id_filiere) VALUES ('M2 Economie appliquée - Data Analyst Etudes pour l''aménagement et l''urbanisme', 'Master', 2, 2, 15);
INSERT INTO formations (nom, niveau, id_ecole, id_batiment, id_filiere) VALUES ('M1&2 Gestion des ressources humaines et mobilité internationale', 'Master', 2, 2, 15);
INSERT INTO formations (nom, niveau, id_ecole, id_batiment, id_filiere) VALUES ('Préparation à l''agrégation de Mathématiques - Propédeutique à la préparation concours interne agrégation mathématiques', 'Prépa', 2, 2, 17);
INSERT INTO formations (nom, niveau, id_ecole, id_batiment, id_filiere) VALUES ('L1&2 Lettres', 'Licence générale', 2, 2, 17);
INSERT INTO formations (nom, niveau, id_ecole, id_batiment, id_filiere) VALUES ('L3 Lettres - Lettres Modernes', 'Licence générale', 2, 2, 17);
INSERT INTO formations (nom, niveau, id_ecole, id_batiment, id_filiere) VALUES ('L1&2 Lettres - Enseignement du 1er degré', 'Licence générale', 2, 2, 17);
INSERT INTO formations (nom, niveau, id_ecole, id_batiment, id_filiere) VALUES ('L3 Géographie et aménagement - Enseignement du 1er degré', 'Licence générale', 2, 2, 17);
INSERT INTO formations (nom, niveau, id_ecole, id_batiment, id_filiere) VALUES ('L3 Géographie et aménagement - Enseignement du 2nd degré', 'Licence générale', 2, 2, 17);
INSERT INTO formations (nom, niveau, id_ecole, id_batiment, id_filiere) VALUES ('L3 Histoire - Enseignement du 1er degré', 'Licence générale', 2, 2, 17);
INSERT INTO formations (nom, niveau, id_ecole, id_batiment, id_filiere) VALUES ('L3 Histoire - Enseignement du 2nd degré', 'Licence générale', 2, 2, 17);
INSERT INTO formations (nom, niveau, id_ecole, id_batiment, id_filiere) VALUES ('L3 Sociologie - Métiers de l''enseignement', 'Licence générale', 2, 2, 17);
INSERT INTO formations (nom, niveau, id_ecole, id_batiment, id_filiere) VALUES ('M1&2 Métiers de l''enseignement, de l''éducation et de la formation (MEEF), 1er degré - Education à l''environnement et au développement durable', 'Master', 2, 2, 17);
INSERT INTO formations (nom, niveau, id_ecole, id_batiment, id_filiere) VALUES ('M1&2 Métiers de l''enseignement, de l''éducation et de la formation (MEEF), 2nd degré - Anglais ou espagnol', 'Master', 2, 2, 17);
INSERT INTO formations (nom, niveau, id_ecole, id_batiment, id_filiere) VALUES ('M1&2 Métiers de l''enseignement, de l''éducation et de la formation (MEEF), 1er degré - Lettres', 'Master', 2, 2, 17);
INSERT INTO formations (nom, niveau, id_ecole, id_batiment, id_filiere) VALUES ('M1&2 Métiers de l''enseignement, de l''éducation et de la formation (MEEF), 2nd degré - Lettres', 'Master', 2, 2, 17);
INSERT INTO formations (nom, niveau, id_ecole, id_batiment, id_filiere) VALUES ('M1&2 Métiers de l''enseignement, de l''éducation et de la formation (MEEF), 2nd degré - Mathématiques', 'Master', 2, 2, 17);
INSERT INTO formations (nom, niveau, id_ecole, id_batiment, id_filiere) VALUES ('M1&2 Métiers de l''enseignement, de l''éducation et de la formation (MEEF), 1er degré - Histoire Géographie', 'Master', 2, 2, 17);
INSERT INTO formations (nom, niveau, id_ecole, id_batiment, id_filiere) VALUES ('M1&2 Métiers de l''enseignement, de l''éducation et de la formation (MEEF), 2nd degré - Histoire Géographie', 'Master', 2, 2, 17);
INSERT INTO formations (nom, niveau, id_ecole, id_batiment, id_filiere) VALUES ('M1&2 Métiers de l''enseignement, de l''éducation et de la formation (MEEF), 1er degré - Education Physique et Sportive', 'Master', 2, 2, 17);
INSERT INTO formations (nom, niveau, id_ecole, id_batiment, id_filiere) VALUES ('M1&2 Métiers de l''enseignement, de l''éducation et de la formation (MEEF), 2nd degré - Education Physique et Sportive', 'Master', 2, 2, 17);
INSERT INTO formations (nom, niveau, id_ecole, id_batiment, id_filiere) VALUES ('M2 Information géographique : analyse spatiale et télédétection', 'Master', 1, 1, 18);
INSERT INTO formations (nom, niveau, id_ecole, id_batiment, id_filiere) VALUES ('M2 Cartographie', 'Master', 1, 1, 18);
INSERT INTO formations (nom, niveau, id_ecole, id_batiment, id_filiere) VALUES ('M1 Arts, Lettres et Civilisations - Mondes anglophones. Discours, cultures, créations', 'Master', 2, 2, 18);
INSERT INTO formations (nom, niveau, id_ecole, id_batiment, id_filiere) VALUES ('M2 Arts, Lettres et Civilisations - Mondes anglophones. Discours, cultures, créations', 'Master', 2, 2, 18);
INSERT INTO formations (nom, niveau, id_ecole, id_batiment, id_filiere) VALUES ('M1 Arts, Lettres et Civilisations - Mondes hispanophones. Ecritures, cultures, créations', 'Master', 2, 2, 18);
INSERT INTO formations (nom, niveau, id_ecole, id_batiment, id_filiere) VALUES ('M2 Arts, Lettres et Civilisations - Mondes hispanophones. Ecritures, cultures, créations', 'Master', 2, 2, 18);
INSERT INTO formations (nom, niveau, id_ecole, id_batiment, id_filiere) VALUES ('Photogrammétrie, positionnement et mesures de déformations', 'Mastère spécialisé', 1, 1, 18);
INSERT INTO formations (nom, niveau, id_ecole, id_batiment, id_filiere) VALUES ('Diplôme d’ingénieur en géomatique', 'Diplôme d''ingénieur', 1, 1, 18);
INSERT INTO formations (nom, niveau, id_ecole, id_batiment, id_filiere) VALUES ('École doctorale Organisations, Marchés, Institutions', 'Doctorat', 7, 2, 18);
INSERT INTO formations (nom, niveau, id_ecole, id_batiment, id_filiere) VALUES ('École doctorale Sciences de la Vie et de la Santé', 'Doctorat', 7, 2, 18);
INSERT INTO formations (nom, niveau, id_ecole, id_batiment, id_filiere) VALUES ('École doctorale Cultures et Sociétés', 'Doctorat', 7, 2, 18);
INSERT INTO formations (nom, niveau, id_ecole, id_batiment, id_filiere) VALUES ('École doctorale Santé Publique', 'Doctorat', 7, 2, 18);
INSERT INTO formations (nom, niveau, id_ecole, id_batiment, id_filiere) VALUES ('École doctorale Agriculture Alimentation Biologie Environnement Santé', 'Doctorat', 7, 2, 18);
INSERT INTO formations (nom, niveau, id_ecole, id_batiment, id_filiere) VALUES ('École doctorale Organisations, Marchés, Institutions', 'Doctorat', 7, 2, 18);
INSERT INTO formations (nom, niveau, id_ecole, id_batiment, id_filiere) VALUES ('École doctorale Ville, Transports et Territoires', 'Doctorat', 7, 2, 18);
INSERT INTO formations (nom, niveau, id_ecole, id_batiment, id_filiere) VALUES ('École doctorale Sciences, Ingénierie et Environnement', 'Doctorat', 7, 2, 18);
INSERT INTO formations (nom, niveau, id_ecole, id_batiment, id_filiere) VALUES ('École doctorale Agriculture Alimentation Biologie Environnement Santé', 'Doctorat', 7, 2, 18);
INSERT INTO formations (nom, niveau, id_ecole, id_batiment, id_filiere) VALUES ('École doctorale Sciences, Ingénierie et Environnement', 'Doctorat', 7, 2, 18);
INSERT INTO formations (nom, niveau, id_ecole, id_batiment, id_filiere) VALUES ('École doctorale Ville, Transports et Territoires', 'Doctorat', 7, 2, 18);
INSERT INTO formations (nom, niveau, id_ecole, id_batiment, id_filiere) VALUES ('École doctorale Agriculture Alimentation Biologie Environnement Santé', 'Doctorat', 7, 2, 18);
INSERT INTO formations (nom, niveau, id_ecole, id_batiment, id_filiere) VALUES ('École doctorale Mathématiques et STIC', 'Doctorat', 7, 2, 18);
INSERT INTO formations (nom, niveau, id_ecole, id_batiment, id_filiere) VALUES ('École doctorale Culture et Sociétés', 'Doctorat', 7, 2, 18);
INSERT INTO formations (nom, niveau, id_ecole, id_batiment, id_filiere) VALUES ('École doctorale Mathématiques et STIC', 'Doctorat', 7, 2, 18);
INSERT INTO formations (nom, niveau, id_ecole, id_batiment, id_filiere) VALUES ('École doctorale Organisations, Marchés, Institutions', 'Doctorat', 7, 2, 18);
INSERT INTO formations (nom, niveau, id_ecole, id_batiment, id_filiere) VALUES ('École doctorale Cultures et Sociétés', 'Doctorat', 7, 2, 18);
INSERT INTO formations (nom, niveau, id_ecole, id_batiment, id_filiere) VALUES ('Génie thermique et énergie', 'DUT', 6, 7, 19);
INSERT INTO formations (nom, niveau, id_ecole, id_batiment, id_filiere) VALUES ('Gestion et maintenance des installations énergétiques', 'Licence professionnelle', 6, 7, 19);
INSERT INTO formations (nom, niveau, id_ecole, id_batiment, id_filiere) VALUES ('Performance énergétique environnementale des bâtiments', 'Licence professionnelle', 6, 7, 19);
INSERT INTO formations (nom, niveau, id_ecole, id_batiment, id_filiere) VALUES ('Vente de produits et services énergétiques', 'Licence professionnelle', 6, 7, 19);
INSERT INTO formations (nom, niveau, id_ecole, id_batiment, id_filiere) VALUES ('Filière Énergies renouvelables et efficacité énergétique', 'Diplôme d''ingénieur', 4, 5, 19);
INSERT INTO formations (nom, niveau, id_ecole, id_batiment, id_filiere) VALUES ('Petroleum Data Management', 'Mastère spécialisé', 1, 1, 19);
INSERT INTO formations (nom, niveau, id_ecole, id_batiment, id_filiere) VALUES ('Sociologie - Métiers de la ville et de l''environnement', 'Licence générale', 2, 2, 20);
INSERT INTO formations (nom, niveau, id_ecole, id_batiment, id_filiere) VALUES ('Géomatique et environnement', 'Licence professionnelle', 1, 1, 20);
INSERT INTO formations (nom, niveau, id_ecole, id_batiment, id_filiere) VALUES ('Qualité, hygiène, sécurité, santé, environnement', 'Licence professionnelle', 2, 2, 20);
INSERT INTO formations (nom, niveau, id_ecole, id_batiment, id_filiere) VALUES ('Maintenance et technologie : systèmes pluritechniques - Technologies et équipements du véhicule - TEV option Equipements électriques électroniques du véhicule (3EV)', 'Licence professionnelle', 2, 2, 20);
INSERT INTO formations (nom, niveau, id_ecole, id_batiment, id_filiere) VALUES ('Métiers de la protection et de la gestion de l''environnement - Technicien spécialisé en dépollution des sites pollués', 'Licence professionnelle', 2, 2, 20);
INSERT INTO formations (nom, niveau, id_ecole, id_batiment, id_filiere) VALUES ('M1&2 Qualité, Hygiène, Sécurité (QSE)', 'Master', 2, 2, 20);
INSERT INTO formations (nom, niveau, id_ecole, id_batiment, id_filiere) VALUES ('M2 Qualité, Hygiène, Sécurité - Qualité Maintenance Sûreté (QMS)', 'Master', 2, 2, 20);
INSERT INTO formations (nom, niveau, id_ecole, id_batiment, id_filiere) VALUES ('M1 Risques et environnement', 'Master', 2, 2, 20);
INSERT INTO formations (nom, niveau, id_ecole, id_batiment, id_filiere) VALUES ('M2 Risques et environnement - Environnement et géomatériaux', 'Master', 2, 2, 20);
INSERT INTO formations (nom, niveau, id_ecole, id_batiment, id_filiere) VALUES ('M1 Risques et environnement - Géorisques', 'Master', 2, 2, 20);
INSERT INTO formations (nom, niveau, id_ecole, id_batiment, id_filiere) VALUES ('M2 Développement durable, management environnemental et géomatique', 'Master', 1, 1, 20);
INSERT INTO formations (nom, niveau, id_ecole, id_batiment, id_filiere) VALUES ('Filière Énergies renouvelables et efficacité énergétique', 'Diplôme d''ingénieur', 4, 5, 20);
INSERT INTO formations (nom, niveau, id_ecole, id_batiment, id_filiere) VALUES ('Management de la chaine du froid', 'Licence professionnelle', 5, 6, 21);
INSERT INTO formations (nom, niveau, id_ecole, id_batiment, id_filiere) VALUES ('M2 Transport, mobilités, réseaux - Transport, Mobilité', 'Master', 2, 2, 21);
INSERT INTO formations (nom, niveau, id_ecole, id_batiment, id_filiere) VALUES ('Organisation et gestion des établissements hôteliers et de restauration - Restauration Collective et Commerciale', 'Licence professionnelle', 2, 2, 22);
INSERT INTO formations (nom, niveau, id_ecole, id_batiment, id_filiere) VALUES ('Organisation et gestion des établissements hôteliers et de restauration - Management International de l''Hôtellerie', 'Licence professionnelle', 2, 2, 22);
INSERT INTO formations (nom, niveau, id_ecole, id_batiment, id_filiere) VALUES ('Langues Etrangères appliquées - Anglais-Espagnol -  Tourisme ou Anglais-Allemand – Tourisme', 'Licence générale', 2, 2, 23);
INSERT INTO formations (nom, niveau, id_ecole, id_batiment, id_filiere) VALUES ('Guide conférencier', 'Licence professionnelle', 2, 2, 23);
INSERT INTO formations (nom, niveau, id_ecole, id_batiment, id_filiere) VALUES ('Métiers du Tourisme : commercialisation des produits touristiques - Nouvelles technologies de l''Information et de la Communication (NTIC)', 'Licence professionnelle', 2, 2, 23);
INSERT INTO formations (nom, niveau, id_ecole, id_batiment, id_filiere) VALUES ('Métiers du Tourisme et des Loisirs - Management de casinos', 'Licence professionnelle', 2, 2, 23);
INSERT INTO formations (nom, niveau, id_ecole, id_batiment, id_filiere) VALUES ('Tourisme et loisirs sportifs', 'Licence professionnelle', 2, 2, 23);
INSERT INTO formations (nom, niveau, id_ecole, id_batiment, id_filiere) VALUES ('M1 Tourisme', 'Master', 2, 2, 23);
INSERT INTO formations (nom, niveau, id_ecole, id_batiment, id_filiere) VALUES ('M2 Tourisme - Destination management', 'Master', 2, 2, 23);
INSERT INTO formations (nom, niveau, id_ecole, id_batiment, id_filiere) VALUES ('M2 Tourisme - Luxury and hospitality', 'Master', 2, 2, 23);
INSERT INTO formations (nom, niveau, id_ecole, id_batiment, id_filiere) VALUES ('M2 Tourisme - Meeting and event industry', 'Master', 2, 2, 23);